<a href="https://colab.research.google.com/github/alliwene/gb-november-grp2-health-insurance/blob/main/dhs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive
from google.colab import drive # import drive from google colab
import os, random 
ROOT = "/content/drive"     # default location for the drive
 
drive.mount(ROOT)

Mounted at /content/drive

In [2]:
# set file path
path = "/content/drive/MyDrive"
os.chdir(path)
!ls # list files in the path

 1-s2.0-S2352340918313520-mmc2.xlsx  'Colab Notebooks'	 NGIR7AFL.SAV

In [3]:
# install pyreadstat to read the spss file
!pip install pyreadstat --quiet

     |████████████████████████████████| 2.4MB 5.3MB/s

In [4]:
# import required libraries 

import pandas as pd
import numpy as np 
import pyreadstat
from pprint import pprint

## Load Data and Clean

In [5]:
# read in the data to a dataframe and get corresponding metadata
df, meta = pyreadstat.read_sav('NGIR7AFL.SAV')
df.head()

            CASEID V000  V001  V002  ...  S434L$3  S434L$4  S434L$5  S434L$6
0         1   1  2  NG7   1.0   1.0  ...      NaN      NaN      NaN      NaN
1         1   6  4  NG7   1.0   6.0  ...      NaN      NaN      NaN      NaN
2         1  11  1  NG7   1.0  11.0  ...      NaN      NaN      NaN      NaN
3         1  25  2  NG7   1.0  25.0  ...      NaN      NaN      NaN      NaN
4         1  30  1  NG7   1.0  30.0  ...      NaN      NaN      NaN      NaN

[5 rows x 5394 columns]

In [6]:
df.shape

(41821, 5394)

In [7]:
# check first 10 column labels from metadata
pprint(meta.column_labels[:10])

['Case Identification',
 'Country code and phase',
 'Cluster number',
 'Household number',
 "Respondent's line number",
 'Ultimate area unit',
 "Women's individual sample weight (6 decimals)",
 'Month of interview',
 'Year of interview',
 'Date of interview (CMC)']

In [8]:
# check if target column in column labels 
'Covered by health insurance' in meta.column_labels

True

In [9]:
# get dictionary with column name as key and column label as value from metadata
# print first 10 items
labels_dict = meta.column_names_to_labels
pprint(list(labels_dict.items())[:10])

[('CASEID', 'Case Identification'),
 ('V000', 'Country code and phase'),
 ('V001', 'Cluster number'),
 ('V002', 'Household number'),
 ('V003', "Respondent's line number"),
 ('V004', 'Ultimate area unit'),
 ('V005', "Women's individual sample weight (6 decimals)"),
 ('V006', 'Month of interview'),
 ('V007', 'Year of interview'),
 ('V008', 'Date of interview (CMC)')]

In [10]:
# get key from value in dict
print(list(labels_dict.keys())[list(labels_dict.values()).index(
    'Covered by health insurance')])

V481

In [11]:
# get variable names for column with categorical variables from metadata
# print first 5 items
variable_values = meta.variable_value_labels   
pprint(list(variable_values.items())[:5])

[('V013',
  {1.0: '15-19',
   2.0: '20-24',
   3.0: '25-29',
   4.0: '30-34',
   5.0: '35-39',
   6.0: '40-44',
   7.0: '45-49'}),
 ('V014',
  {1.0: 'Month and year - information complete',
   2.0: 'Month and age - year imputed',
   3.0: 'Year and age - month imputed',
   4.0: 'Year and age - year ignored',
   5.0: 'Year - age/month imputed',
   6.0: 'Age - year/month imputed',
   7.0: 'Month - age/year imputed',
   8.0: 'None - all imputed'}),
 ('V015',
  {1.0: 'Completed',
   2.0: 'Not at home',
   3.0: 'Postponed',
   4.0: 'Refused',
   5.0: 'Partially completed',
   6.0: 'Respondent incapacitated',
   7.0: 'Other'}),
 ('V018', {0.0: 'No calendar'}),
 ('V019', {0.0: 'No calendar'})]

In [12]:
# drop caseid column
df.drop('CASEID', axis=1, inplace=True)

In [13]:
# check if unique values of a col is equal to 1
# coulmns like this would be useless for a model
empty_unique = []
for col in df.columns:
  if len(df[col].unique()) == 1:
    empty_unique.append(col) 

# print(empty_unique)
print(len(empty_unique))

2904

In [14]:
# drop the columns
df.drop(empty_unique, axis=1, inplace=True)
df.head()

   V001  V002  V003  V004  ...  S434IX$1  S434IZ$1  S434K$1  S434L$1
0   1.0   1.0   2.0   1.0  ...       0.0       0.0      0.0      NaN
1   1.0   6.0   4.0   1.0  ...       NaN       NaN      NaN      NaN
2   1.0  11.0   1.0   1.0  ...       0.0       0.0      0.0      NaN
3   1.0  25.0   2.0   1.0  ...       0.0       0.0      0.0      NaN
4   1.0  30.0   1.0   1.0  ...       NaN       NaN      NaN      NaN

[5 rows x 2489 columns]

In [15]:
# df.loc[:, df.isna().mean() < .2]

In [16]:
# filter dataframe using columns with no null values 
df = df.loc[:, df.isna().sum() == 0]
df.head()

   V001  V002  V003  V004  ...  S1108BA  S1108BC  S1108BD  S1108BF
0   1.0   1.0   2.0   1.0  ...      1.0      0.0      1.0      0.0
1   1.0   6.0   4.0   1.0  ...      1.0      1.0      0.0      0.0
2   1.0  11.0   1.0   1.0  ...      1.0      0.0      1.0      0.0
3   1.0  25.0   2.0   1.0  ...      0.0      0.0      1.0      0.0
4   1.0  30.0   1.0   1.0  ...      0.0      0.0      1.0      0.0

[5 rows x 251 columns]

In [17]:
# check for columns with duplicate labels in df
duplicate_list = []
for col in df.columns:
  if '$' in col:
    duplicate_list.append(col)
print(duplicate_list)

['V304$01', 'V304$02', 'V304$03', 'V304$05', 'V304$06', 'V304$07', 'V304$08', 'V304$09', 'V304$10', 'V304$11', 'V304$13', 'V304$14', 'V304$16', 'V304$17', 'V304$18', 'VCAL$1', 'VCAL$2']

In [18]:
# drop duplicate column labels 
df.drop(duplicate_list, axis=1, inplace=True)
df.head()

   V001  V002  V003  V004  ...  S1108BA  S1108BC  S1108BD  S1108BF
0   1.0   1.0   2.0   1.0  ...      1.0      0.0      1.0      0.0
1   1.0   6.0   4.0   1.0  ...      1.0      1.0      0.0      0.0
2   1.0  11.0   1.0   1.0  ...      1.0      0.0      1.0      0.0
3   1.0  25.0   2.0   1.0  ...      0.0      0.0      1.0      0.0
4   1.0  30.0   1.0   1.0  ...      0.0      0.0      1.0      0.0

[5 rows x 234 columns]

In [ ]:
# set out target variable as a separate dataframe
target = pd.DataFrame(df['V481'])
target.head()

   V481
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0

In [ ]:
# make a copy of the dataframe
df1 = df.copy()

In [ ]:
# drop target column from df1
df1.drop('V481', axis = 1, inplace = True)

In [ ]:
# create a filter with columns that has correlation >0.04 with target column
filter = df1.apply(lambda x: target.corrwith(x).abs()) > 0.04
filter

       V001   V002   V003   V004  ...  S1108BA  S1108BC  S1108BD  S1108BF
V481  False  False  False  False  ...    False    False    False    False

[1 rows x 233 columns]

In [ ]:
# filter df1 with the filter
df1 = df1.loc[:, [x for x in filter.iloc[0]]]
df1.head()

     V008A    V010    V011  V012  V013  ...  S653T  S815E  S815F  S815G  S1108AI
0  43345.0  1978.0   939.0  40.0   6.0  ...    1.0    0.0    0.0    0.0      1.0
1  43344.0  2002.0  1230.0  16.0   1.0  ...    0.0    1.0    0.0    0.0      1.0
2  43345.0  1981.0   977.0  37.0   5.0  ...    0.0    0.0    1.0    0.0      1.0
3  43345.0  1990.0  1091.0  27.0   3.0  ...    0.0    0.0    0.0    0.0      0.0
4  43345.0  1989.0  1073.0  29.0   3.0  ...    1.0    0.0    0.0    0.0      1.0

[5 rows x 65 columns]

In [ ]:
df1.shape

(41821, 65)

In [ ]:
# change column labels to column names 
df1.columns = df1.columns.map(labels_dict)
df1.head()

   Date of interview Century Day Code (CDC)  ...  Malaria can be fully cured by medicine
0                                   43345.0  ...                                     1.0
1                                   43344.0  ...                                     1.0
2                                   43345.0  ...                                     1.0
3                                   43345.0  ...                                     0.0
4                                   43345.0  ...                                     1.0

[5 rows x 65 columns]

In [45]:
# make another copy of df and drop target column
df2 = df.copy()
df2.drop('V481', axis = 1, inplace = True)

In [46]:
# Calculate the correlation matrix and take the absolute value
corr_matrix = df2.corr().abs()

In [47]:
# Create a True/False mask and apply it
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
tri_df = corr_matrix.mask(mask)

In [48]:
# List column names of highly correlated features (r > 0.4)
to_drop = [c for c in tri_df.columns if any(tri_df[c] > 0.4)]
print(len(to_drop))

136

In [49]:
# Drop the features in the to_drop list
df2.drop(to_drop, axis=1, inplace=True)
df2.shape

(41821, 97)

In [24]:
# change column labels to column names 
df2.columns = df2.columns.map(labels_dict)
df2.head()

   Women's individual sample weight (6 decimals)  ...  Only weak children can die from malaria
0                                      1335530.0  ...                                      0.0
1                                      1335530.0  ...                                      0.0
2                                      1335530.0  ...                                      0.0
3                                      1335530.0  ...                                      0.0
4                                      1335530.0  ...                                      0.0

[5 rows x 97 columns]